ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('cart/', views.view_cart, name='view_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=254, null=True)
    
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True)  

    def __str__(self):
         return self.name

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else: 
            return 'There is no image for this'
    
    # def image_url(self):
    #     try:
    #         self.image.url
    #     except:
    #         return 'static/images/placeholder.pngstatic/images/placeholder.pngstatic/images/placeholder.png'

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.quantity}: {self.product}"

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'ShippingAddresses' 

store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Customer, Product, OrderItem, Order, ShippingAddress
from django.views import generic

# Create your views here.
def index(request):
    context = {
        'products': Product.objects.all()
    }
    return render(request, 'store/index.html', context)

def view_cart(request):
    context = {
        'products': Product.objects.all()
    }
    return render(request, 'store/cart.html', context)

def checkout(request):
    context = {
        'products': Product.objects.all()
    }
    return render(request, 'store/index.html', context)

store/templates/store/cart.html
{% extends "store/layout.html" %}
{% block content %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('.btn').forEach( button => {
      button.onlick = () => {
        window.location.href = `store/${button.dataset.location}`;
        console.log(button.dataset.location)
      }
    });
  });
</script>

<div class="row">
  <div class="col s12 m12" style="padding: 0px;">
    <div class="card cyan darken-2">
      <div class="card-action">
        <button class="btn waves-effect waves-light" type="submit" name="action" style="padding-left: 0;" data-location="index">
          <i class="material-icons left back-forward">arrow_left</i>Continue Shopping
        </button>
        <button class="btn waves-effect waves-light float-right" type="submit" name="action" style="padding-right: 0;" data-location="checkout">Checkout
          <i class="material-icons right back-forward">arrow_right</i>
        </button>
      </div>
      <div class="card-content white-text">
        <span class="card-title">Card Title</span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
    </div>
  </div>
</div>
<table class="responsive-table">
  <thead>
    <tr>
        <th>Image</th>
        <th>Item Name</th>
        <th>Item Price</th>
        <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    {% for product in products %}
    <tr>
      <td><img class="activator" src="{{ product.image_url }}" style="height: 25px; width: 40px;"></td>
      <td>{{ product.name }}</td>
      <td>{{ product.price }}</td>
      <td>
        <!-- Arrows to move up and down -->
        <!-- <div style="float: left; width: 20px; height: 20px; padding-right: 10px;">
          <i class="material-icons blue-text text-lighten-1" style="font-size: 40px; cursor: pointer;">arrow_drop_up</i>
          <i class="material-icons blue-text text-lighten-1" style="font-size: 40px; cursor: pointer;">arrow_drop_down</i>
        </div> -->
        {{ product.price }} 
        <span class="float-right"><i class="material-icons red-text lighten-1" id="delete">delete</i></span>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

store/templates/store/index.html
{% extends "store/layout.html" %}

{% block content %}
  <div class="row" style="padding-top: 20px;">
    {% for product in products %}
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light thumbnail" style="height: 200px; width: 300px;">
          <img class="activator" src="{{ product.image_url }}">
        </div>
        <div class="card-content cyan lighten-5">
          <span class="card-title activator grey-text text-darken-4" style="font-size: 19px;">{{ product.name }} <span style="float: right"><i class="material-icons right">more_vert</i></span> </span>
          <div class="card-action" >
            <span style="font-size: 18px;">${{ product.price | floatformat:2 }}</span>
          <button class="btn waves-effect waves-light float-right" type="submit" name="action">Add to cart
              <i class="material-icons right">add_shopping_cart</i>
            </button>
          </div>
        </div>
        <div class="card-reveal cyan lighten-5">
          <span class="card-title grey-text text-darken-4">{{ product.name }}<i class="material-icons right">close</i></span>
          <p>This {{ product.name }} which costs {{ product.price }} a piece is a good purchase if you love good {{ product.name }}.</p>
        </div>
      </div>  
    </div>
    {% endfor %}
  </div>
{% endblock content %}

store/templates/store/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">    
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
  <link rel="stylesheet" href="{% static '/css/styles.css' %}">
  <title>Ecom</title>
</head>
<body> 
  <div>
    <nav>
      <div class="nav-wrapper cyan darken-3">
        <div class="container" style="padding-left: 3rem; padding-right: 2rem;">
          <a href="{% url 'store:index' %}" class="brand-logo"><i class="material-icons" style="font-size: 2.5rem;">home</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'store:view_cart' %}"><i class="material-icons" style="font-size: 2rem;">shopping_cart</i></a></li>
        </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    {% block content %}
    
    {% endblock content %}
  </div>
</body>
</html>